version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped
    environment:
        - discovery.type=single-node
        - node.name=elasticsearch
        - cluster.name=es-docker-cluster
        - bootstrap.memory_lock=true
        - xpack.security.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
    volumes:
        - ./elasticsearch/data:/usr/share/elasticsearch/data:rw
  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.0
    restart: unless-stopped
    volumes:
        - type: bind
          source: ./logstash/config/logstash.yml
          target: /usr/share/logstash/config/logstash.yml
          read_only: true
        - type: bind
          source: ./logstash/config/pipelines.yml
          target: /usr/share/logstash/config/pipelines.yml
          read_only: true
        - type: bind
          source: ./logstash/pipeline
          target: /usr/share/logstash/pipeline
          read_only: true
    ports:
        - "5000:5000"
        - "5001:5001"
        - "5002:5002"
        - "5003:5003"
        - "5004:5004"
        - "5005:5005"
        - "5006:5006"
        - "9600:9600"
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
  postgresql-master:
    image: docker.io/bitnami/postgresql:11
    ports:
      - 5432:5432
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
  postgresql-slave:
      image: docker.io/bitnami/postgresql:11
      ports:
        - 5433:5432
      depends_on:
        - postgresql-master
      environment:
        - POSTGRESQL_REPLICATION_MODE=slave
        - POSTGRESQL_REPLICATION_USER=repl_user
        - POSTGRESQL_REPLICATION_PASSWORD=repl_password
        - POSTGRESQL_MASTER_HOST=postgresql-master
        - POSTGRESQL_PASSWORD=my_password
        - POSTGRESQL_MASTER_PORT_NUMBER=5432
        - ALLOW_EMPTY_PASSWORD=yes
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    environment:
      - POSTGRES_DB=ticketServiceDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - 5438:5432
#  mysql2:
#      image: mysql:latest
#      ports:
#        - "3307:3306"
#      environment:
#        MYSQL_ROOT_USER: root
#        MYSQL_ROOT_PASSWORD: password
#        MYSQL_DATABASE: ticketServiceDB
#        MYSQL_USER: jane.garciu
#        MYSQL_PASSWORD: password
  eureka-server:
    image: eureka-server:latest
    ports:
      - "8761:8761"
    depends_on:
      - logstash
    links:
      - logstash
  gateway-server:
    image: gateway-server:latest
    restart: on-failure
    depends_on:
      - eureka-server
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka-server:8761/eureka
    ports:
      - "8762:8762"
  authorisation-server:
    image: authorisation-server:latest
    restart: on-failure
    depends_on:
      - eureka-server
      - gateway-server
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka-server:8761/eureka
    expose:
      - 8206
  cache-service:
    image: cache-service:latest
    restart: on-failure
    depends_on:
      - eureka-server
      - gateway-server
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka-server:8761/eureka
    ports:
      - 8202:8202
  cache-service2:
    image: cache-service2:latest
    restart: on-failure
    depends_on:
      - eureka-server
      - gateway-server
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka-server:8761/eureka
    ports:
      - 8203:8203
  flight-service:
    image: flight-service:latest
    depends_on:
    - eureka-server
    - gateway-server
    - postgresql-master
    environment:
      - JAVA_OPTS=
      - DEUREKA_SERVER=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql-master:5432/my_database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=my_password

    expose:
      - 8200
  ticket-service:
    image: ticket-service:latest
    depends_on:
      - eureka-server
      - gateway-server
      - postgresql
    environment:
      - JAVA_OPTS=
      - DEUREKA_SERVER=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/ticketServiceDB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    expose:
      - 8201
#networks:
#  elk:
#    driver: bridge
volumes:
  elasticsearch:
  postgresql_master_data:
    driver: local
